drop table if exists espionage_report;

CREATE TABLE espionage_report (
    id INT UNSIGNED NOT NULL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    info_level TINYINT UNSIGNED NOT NULL,
    galaxy TINYINT UNSIGNED NOT NULL,
    system SMALLINT UNSIGNED NOT NULL,
    position TINYINT UNSIGNED NOT NULL,
    type TINYINT UNSIGNED NOT NULL,
    planet_name VARCHAR(100) NOT NULL,
    player_name VARCHAR(100) NOT NULL,
    player_status VARCHAR(20) NOT NULL,
    activity BOOLEAN NOT NULL,
    activity_time TINYINT UNSIGNED NULL,
    metal INT UNSIGNED NOT NULL,
    crystal INT UNSIGNED NOT NULL,
    deut INT UNSIGNED NOT NULL,
    energy MEDIUMINT UNSIGNED NOT NULL,
    light_fighter INT UNSIGNED NULL,
    heavy_fighter INT UNSIGNED NULL,
    cruiser INT UNSIGNED NULL,
    battleship INT UNSIGNED NULL,
    battlecruiser INT UNSIGNED NULL,
    bomber INT UNSIGNED NULL,
    destroyer INT UNSIGNED NULL,
    death_star INT UNSIGNED NULL,
    small_cargo INT UNSIGNED NULL,
    large_cargo INT UNSIGNED NULL,
    colony_ship INT UNSIGNED NULL,
    recycler INT UNSIGNED NULL,
    espionage_probe INT UNSIGNED NULL,
    solar_satellite INT UNSIGNED NULL,
    rocket_launcher INT UNSIGNED NULL,
    light_laser INT UNSIGNED NULL,
    heavy_laser INT UNSIGNED NULL,
    ion_cannon INT UNSIGNED NULL,
    gauss_cannon INT UNSIGNED NULL,
    plasma_turret INT UNSIGNED NULL,
    small_shield INT UNSIGNED NULL,
    large_shield INT UNSIGNED NULL,
    anti_ballistic INT UNSIGNED NULL,
    interplanetary INT UNSIGNED NULL,
    metal_mine INT UNSIGNED NULL,
    crystal_mine INT UNSIGNED NULL,
    deut_mine INT UNSIGNED NULL,
    solar_plant INT UNSIGNED NULL,
    robotics INT UNSIGNED NULL,
    shipyard INT UNSIGNED NULL,
    metal_storage INT UNSIGNED NULL,
    crystal_storage INT UNSIGNED NULL,
    deut_storage INT UNSIGNED NULL,
    research_lab INT UNSIGNED NULL,
    fusion_reactor INT UNSIGNED NULL,
    nanite INT UNSIGNED NULL,
    terraformer INT UNSIGNED NULL,
    alliance_depot INT UNSIGNED NULL,
    missile_silo INT UNSIGNED NULL,
    space_dock INT UNSIGNED NULL,
    lunar_base INT UNSIGNED NULL,
    sensor_phalanx INT UNSIGNED NULL,
    jump_gate INT UNSIGNED NULL,
    energy_tech INT UNSIGNED NULL,
    laser INT UNSIGNED NULL,
    ion INT UNSIGNED NULL,
    hyperspace INT UNSIGNED NULL,
    plasma INT UNSIGNED NULL,
    espionage INT UNSIGNED NULL,
    computer INT UNSIGNED NULL,
    astrophysics INT UNSIGNED NULL,
    intergalactic INT UNSIGNED NULL,
    graviton INT UNSIGNED NULL,
    combustion_drive INT UNSIGNED NULL,
    impulse_drive INT UNSIGNED NULL,
    hyperspace_drive INT UNSIGNED NULL,
    weapons_upgrade INT UNSIGNED NULL,
    shielding_upgrade INT UNSIGNED NULL,
    armor_upgrade INT UNSIGNED NULL,
    INDEX idx_espionage_header USING BTREE (galaxy , system , position , type , timestamp)
);
